# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_fname', models.CharField(db_column='Farmer_fName', max_length=255)),
                ('farmer_lname', models.CharField(db_column='Farmer_lName', max_length=255)),
                ('farmer_sname', models.CharField(blank=True, db_column='Farmer_sName', max_length=255, null=True)),
                ('farmer_username', models.CharField(db_column='Farmer_userName', max_length=45, unique=True)),
                ('farmer_password', models.CharField(db_column='Farmer_password', max_length=255)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=45)),
                ('location_long', models.CharField(max_length=45)),
                ('location_lat', models.CharField(max_length=45)),
                ('location_description', models.CharField(blank=True, max_length=255, null=True)),
                ('location_created', models.CharField(blank=True, max_length=45, null=True)),
                ('location_updated', models.CharField(blank=True, max_length=45, null=True)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddField(
            model_name='farmers',
            name='farmer_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='farmers.Locations'),
        ),
    ]
