# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='location_created',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='location_updated',
        ),
        migrations.AddField(
            model_name='locations',
            name='nearest_town',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 8, 58, 13, 822602)),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 23, 8, 58, 13, 822625), null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 8, 58, 13, 821857)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 23, 8, 58, 13, 821883), null=True),
        ),
    ]
