# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 09:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_auto_20170323_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 9, 12, 2, 35366)),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 23, 9, 12, 2, 35388), null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 23, 9, 12, 2, 34717)),
        ),
        migrations.AlterField(
            model_name='locations',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 23, 9, 12, 2, 34743), null=True),
        ),
    ]
